### PR TITLE
Fix Ageband by splitting 0-1 to 0-0, 1-1

### PR DESCRIPTION
**Pull request by xtfang-jcr**
Fixes issue #26 

Note that you now have to update Ageband to be Ageband +1, e.g. in our case from `c(0:94)` to `c(0:95)`

### CODE REVIEW

**Comment by DavideMessinaARS** [comment]
The changes in the Ageband parameter is a potential problem since it is not backward compatible.
I will discuss with @RosaMGini on how to solve the issue. (She's on holiday)

In the meantime you can use your version as it is

**Comment by xtfang-jcr** [comment]
Updated my fix to ensure backwards compatibility. Now it will correctly generate `n+1` rows, e.g. for `c(0:94)` it will create 96 agebands.

**Review by DavideMessinaARS — CHANGES_REQUESTED** [review]
Example 6 doesn't seems to be working correctly

Case 1 (0-17 person disappear): image

image

Case 2 (ageband single year): image

**Comment by DavideMessinaARS** [comment]
I've updated example 6 in the branch feat-split_decrease_RAM to run for v14

**Comment by xtfang-jcr** [comment]
Hi Davide,

I took a brief look at your example and I can see how our code wouldn't account for your case, since your age range is like this:   Age_bands = c(0,17,44,64),

This is not how our functions are run since we specify a range of values, i.e. always 0:94 and not specific ages.

Not really sure how to reconcile this right now. I'll take a think and see if I can figure something out. If not, we'll leave out fix only for us locally.

Best,

Tsong

**Comment by xtfang-jcr** [comment]
Hi Davide,

thought about it some more and came to a reasonably practical (but not elegant) solution.

Using an `if` statement it's easy to switch between your solution where you have larger agebands spanning multiple years, and mine. As it stands, I couldn't reach a satisfactory way of dealing with this issue.

Given that e.g. for example 6 we have few specified ages, but the max value in `Age_bands` is larger than the length of `Age_bands`. This is impossible when we specify a range, e.g. `c(0:94)`, where in doing so the max value will always be 1 smaller than the length.


```r
# define function
CPT <- function(Age_bands) {
for (k in 1:length(Age_bands)) {
  if (max(Age_bands) > length(Age_bands)) {
    
    if( k == 1) Agebands_list[[k]] <- paste0(Age_bands[k], "-", Age_bands[k+1])
    if( k > 1 & k != length(Age_bands)) Agebands_list[[k]] <- paste0(Age_bands[k]+1, "-", Age_bands[k+1])          
    if( k == length(Age_bands) & include_remaning_ages == T) Agebands_list[[k]] <- paste0(Age_bands[k]+1, "+")
  } else {
    if(k <= length(Age_bands)) Agebands_list[[k]] <- paste0(Age_bands[k], "-", Age_bands[k])
    if(k == length(Age_bands) & include_remaning_ages == T) Agebands_list[[k+1]] <- paste0(Age_bands[k]+1, "+")
  }
}
  return(Agebands_list)
}
```

```r
# example 6
Agebands_list <- list()
include_remaning_ages = T

Age_bands1 = c(0, 17, 44, 64)
CPT(Age_bands1)
[[1]]
[1] "0-17"

[[2]]
[1] "18-44"

[[3]]
[1] "45-64"

[[4]]
[1] "65+"
```

```r
# how we use it
Age_bands2 = c(0:12)
CPT(Age_bands2)
[[1]]
[1] "0-0"

[[2]]
[1] "1-1"

[[3]]
[1] "2-2"

[[4]]
[1] "3-3"

[[5]]
[1] "4-4"

[[6]]
[1] "5-5"

[[7]]
[1] "6-6"

[[8]]
[1] "7+"
```

**Comment by DavideMessinaARS** [comment]
I think for now this is usable.

However I thought some more too and to me it seems what you want can be computed in the original CountPersonTime call by setting the parameter Age_bands as c(0, 0:94). Is that what you want?

In case it is I would suggest to use the original CountPersonTime functionality and I will add explicitly better instructions in the documentation for your use case.

Otherwise, I can merge the PR and I will add a comment to explain why this part should be fixed and rewritten in the future.
(for example in case we have Age_bands = c(0, 1, 17, 44, 64) and function calling values outside its environment)

**Comment by xtfang-jcr** [comment]
That is a great solution. Sometimes, the ideal and most elegant change is no change at all. Were you inspired by my comment about when stating a range, the max value will always be smaller than the length (which you have proven wrong just now) :)

Indeed, what you stated is what we want. Factually, we're misusing the age band parameter in our use case. We generate `n-n` 'age bands` which are not age bands at all, rather just a single age. I agree that changing our input parameters to produce these rather than altering the code is a much better implementation.

Indeed, please mention this in the documentation. I've adapted our scripts and we will use your original V14 without edits. I think this PR can be closed/rejected.

**Comment by DavideMessinaARS** [comment]
When I was checking the code and various extreme cases I had a flashback of a similar problem I encountered some time ago.
My idea in the past was to simplify the parameters and only use the right-end part of each period in the parameter "Ageband" and to make it consistent with adding the last period with another option (i.e. include_remaning_ages would add the first period too) or remove "include_remaning_ages" option altogether. I decided against it since age has a theoretical minimum of 0 but not a maximum.

Obviously the last time I didn't document it and the result was I promptly forgot about it.
So I want to thank everyone from your team to have taken the time to open an issue and even a PR about it.
This time I've updated the documentation so that in the future when someone has the same issue finding a solution should be much easier.

**Comment by xtfang-jcr** [comment]
That is an interesting anecdote, thanks for sharing. Indeed, as I've mentioned previously as well us at JC are more or less misusing this function since we want agebands of 1 year. However, I'm very happy we reached a satisfactory implementation that allows us to get what we want without any code changes. Thanks also for updating the documentation. That has been very helpful for our implementation.

**Pull request closed without merging**
